---
title: Paramorph
timezone: Europe/Warsaw
collections:
  categories:
    title: Categories
    output: true
  pages:
    title: Pages
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
baseUrl: http://paramorph.github.io
image: http://paramorph.github.io/facebook.png
locale: pl_PL
menu:
- title: Home
  short: Home
  url: "/"
  icon:
- title: Blog
  short: Blog
  url: "/blog"
  icon:
- title: Contact
  short: Contact
  url: "/contact"
  icon:
